/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marko_milosavljevic_chatapplication_Crypto */

#ifndef _Included_marko_milosavljevic_chatapplication_Crypto
#define _Included_marko_milosavljevic_chatapplication_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     marko_milosavljevic_chatapplication_Crypto
 * Method:    crypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_marko_milosavljevic_chatapplication_Crypto_crypt (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
